import * as fs from 'node:fs';
import * as path from 'node:path';
import { definePlugin, PluginFailure } from '../../core/define.ts';
import { Browser } from '../../core/browser.ts';
import { ffmpeg } from '../../core/media.ts';
import { S } from '../_shared/common.ts';

/**
 * image.create — CREATE an image from markup (SVG or HTML+CSS).
 *
 * This is the "image creation" capability: nothing is downloaded, nothing is
 * generated by a model. The caller supplies markup and this plugin rasterises
 * it with a real browser, so the full CSS/SVG feature set is available:
 * gradients, filters, blend modes, web fonts, flex/grid layout, clip-path,
 * SVG paths, text on a path, box shadows, masks.
 */
export default definePlugin({
    id: 'image.create',
    name: 'Create image from SVG/HTML',
    category: 'image',
    description: 'Rasterise SVG or HTML+CSS markup into a PNG/JPG image using a real browser engine.',
    inputs: {
        svg: S.string('Raw SVG markup to render'),
        html: S.string('Raw HTML fragment or full document (alternative to svg)'),
        css: S.string('Extra CSS injected into the page'),
        width: S.int('Canvas width in pixels', { default: 1080, minimum: 1 }),
        height: S.int('Canvas height in pixels', { default: 1920, minimum: 1 }),
        scale: S.number('Device scale factor (2 = 2x resolution)', { default: 1, minimum: 0.5, maximum: 4 }),
        background: S.string('CSS background colour, e.g. #0b1020 or transparent', { default: '#ffffff' }),
        transparent: S.bool('Keep the background transparent (PNG only)', { default: false }),
        out: S.string('Output file name (.png or .jpg)', { default: 'created.png' }),
    },
    outputs: ['image'],
    async run({ input, ctx }) {
        const svg = typeof input.svg === 'string' ? input.svg : '';
        const html = typeof input.html === 'string' ? input.html : '';
        if (!svg && !html) {
            throw new PluginFailure({
                code: 'INVALID_INPUT',
                message: 'Provide either "svg" or "html" markup to render.',
                input: { svg: svg.slice(0, 40), html: html.slice(0, 40) },
                retryable: true,
                hint: 'image.create renders markup you supply — it does not invent content.',
            });
        }
        const width = Number(input.width ?? 1080);
        const height = Number(input.height ?? 1920);
        const scale = Number(input.scale ?? 1);
        const transparent = input.transparent === true;
        const bg = transparent ? 'transparent' : String(input.background ?? '#ffffff');

        const body = svg
            ? svg
            : /<html[\s>]/i.test(html)
              ? html
              : `<!doctype html><html><head><meta charset="utf-8"><style>${String(input.css ?? '')}</style></head><body>${html}</body></html>`;

        const page = /<html[\s>]/i.test(body)
            ? body
            : `<!doctype html><html><head><meta charset="utf-8"><style>
                 html,body{margin:0;padding:0;background:${bg};}
                 #vf-stage{width:${width}px;height:${height}px;overflow:hidden;}
                 svg{display:block;}
               </style></head><body><div id="vf-stage">${body}</div></body></html>`;

        const css = String(input.css ?? '');
        const withCss = css && /<html[\s>]/i.test(page)
            ? page.replace('</head>', `<style>${css}</style></head>`)
            : page;

        const dest = ctx.out(String(input.out ?? 'created.png'));
        const tmpPng = dest.toLowerCase().endsWith('.png') ? dest : dest.replace(/\.(jpe?g)$/i, '.png');

        fs.mkdirSync(path.dirname(tmpPng), { recursive: true });
        const browser = await Browser.launch({ width, height, scale, transparent });
        try {
            await browser.setContent(withCss, ctx.workspaceDir);
            await browser.screenshot(tmpPng, transparent);
        } finally {
            await browser.close();
        }

        if (tmpPng !== dest) {
            await ffmpeg(['-y', '-i', tmpPng, '-q:v', '2', dest]);
            try {
                fs.unlinkSync(tmpPng);
            } catch {
                /* ignore */
            }
        }

        return {
            outputs: [
                {
                    path: dest,
                    kind: 'image',
                    meta: { width, height, scale, engine: 'chromium' },
                },
            ],
        };
    },
});
