/**
 * Regenerate plugins/INDEX.md from the live registry.
 *
 * Run with:  npm run gen:index
 *
 * The index is generated on purpose — a hand-maintained list of 120+ plugins
 * goes stale the moment somebody adds one. This walks the real registry, so
 * INDEX.md always matches what `forge list` reports.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { loadPlugins } from '../core/loader.ts';
import { all } from '../core/registry.ts';
import { projectRoot } from '../core/env.ts';

const OUT = path.join(projectRoot(), 'plugins', 'INDEX.md');
const README = path.join(projectRoot(), 'README.md');
const BEGIN = '<!-- BEGIN GENERATED: categories -->';
const END = '<!-- END GENERATED: categories -->';

/**
 * Rewrite the "Plugin categories" block in README.md.
 *
 * That table used to be hand-maintained and had drifted badly: 21 rows against
 * 16 real categories, counts off by four, and plugins listed twice under
 * different headings. Generating it means the README cannot disagree with
 * `forge categories`.
 */
function updateReadmeCategories(rows: { category: string; plugins: string[] }[]): boolean {
    if (!fs.existsSync(README)) return false;
    const src = fs.readFileSync(README, 'utf8');
    const a = src.indexOf(BEGIN);
    const b = src.indexOf(END);
    if (a === -1 || b === -1) return false;

    const L: string[] = [BEGIN, '', '| Category | Count | Plugins |', '|---|---|---|'];
    for (const r of rows) L.push(`| \`${r.category}\` | ${r.plugins.length} | ${r.plugins.map((id) => `\`${id}\``).join(', ')} |`);
    L.push('');

    fs.writeFileSync(README, src.slice(0, a) + L.join('\n') + src.slice(b), 'utf8');
    return true;
}

/**
 * Map plugin id -> path relative to plugins/.
 *
 * The registry does not carry the source file, so read it back off the tree —
 * the same source of truth the loader uses.
 */
function pathByPluginId(): Map<string, string> {
    const dir = path.join(projectRoot(), 'plugins');
    const out = new Map<string, string>();
    const walk = (d: string): void => {
        for (const e of fs.readdirSync(d, { withFileTypes: true })) {
            const p = path.join(d, e.name);
            if (e.isDirectory()) walk(p);
            else if (/\.(ts|py)$/.test(e.name)) {
                const src = fs.readFileSync(p, 'utf8');
                const m = src.match(/id:\s*['"]([a-zA-Z0-9_.]+)['"]/);
                if (m) out.set(m[1], path.relative(dir, p).replace(/\\/g, '/'));
            }
        }
    };
    walk(dir);
    return out;
}

async function main(): Promise<void> {
    await loadPlugins();
    const files = pathByPluginId();
    const plugins = all().slice().sort((a, b) => a.manifest.id.localeCompare(b.manifest.id));

    const groups = new Map<string, typeof plugins>();
    for (const p of plugins) {
        const key = p.manifest.category;
        groups.set(key, [...(groups.get(key) ?? []), p]);
    }
    const categories = [...groups.keys()].sort();

    const L: string[] = [];
    L.push('# Plugin index');
    L.push('');
    L.push('<!-- GENERATED by `npm run gen:index` — do not edit by hand. -->');
    L.push('');
    L.push(`${plugins.length} plugins across ${categories.length} categories. Path is relative to \`plugins/\`.`);
    L.push('');
    L.push('The folder mirrors the ID: plugin `video.trim` lives at `video/trim.ts`.');
    L.push('Sub-systems get a sub-folder: `voice.voicebox_health` → `voice/voicebox/health.ts`.');
    L.push('');
    L.push('## Contents');
    for (const c of categories) {
        L.push(`- [${c}](#${c}) — ${groups.get(c)!.length}`);
    }
    L.push('');

    for (const c of categories) {
        const list = groups.get(c)!;
        L.push(`## ${c}`);
        L.push('');
        L.push('| id | what it does | engine | file |');
        L.push('| --- | --- | --- | --- |');
        for (const p of list) {
            const m = p.manifest;
            const desc = m.description.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
            L.push(`| \`${m.id}\` | ${desc} | ${m.engine === 'python' ? 'py' : 'ts'} | \`${files.get(m.id) ?? '?'}\` |`);
        }
        L.push('');
    }

    fs.writeFileSync(OUT, L.join('\n'), 'utf8');
    console.log(`wrote ${path.relative(projectRoot(), OUT)} — ${plugins.length} plugins, ${categories.length} categories.`);

    const rows = categories.map((c) => ({
        category: c,
        plugins: groups.get(c)!.map((p) => p.manifest.id).sort(),
    }));
    if (updateReadmeCategories(rows)) {
        console.log(`updated README.md categories block — ${categories.length} categories.`);
    } else {
        console.warn('README.md category markers not found — skipped.');
    }
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
